# Version: 1.0.6
#
# Docker Compose file to spin up two preconfigured containers : MS SQL Server on Linux and OpCon Server.
# You'll need to specify at least VOLUME_PATH and DB_PASSWORD env variables via .env file to get this running with defaults.
#
# Detailed instructions here : https://github.com/SMATechnologies/opcon-docker#docker-compose-instructions
version: '3.7'
networks:
  default:
    name: ${CONTAINER_PREFIX:-opcon}-network
services:
  opcon-mssql:
    image: mcr.microsoft.com/mssql/server:${MSSQL_VERSION:-2017-latest}
    container_name: ${CONTAINER_PREFIX:-opcon}-mssql
    hostname: ${MSSQL_HOSTNAME:-opcon-mssql}
    volumes:
      - type: volume
        source: opcon-mssql
        target: /var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_ADMIN_PASSWORD:?SQL_ADMIN_PASSWORD}
      - TZ=${TZ:-UTC}
    ports:
      - "${MSSQL_PORT:-1433}:1433"
    restart: always
  opcon-core:
    image: ${OPCON_REPOSITORY:-smatechnologies/opcon-server}:${OPCON_VERSION:-19.1-latest}
    container_name: ${CONTAINER_PREFIX:-opcon}-core
    hostname: ${OPCON_HOSTNAME:-opcon-core}
    depends_on:
      - opcon-mssql
    environment:
      - SQL_ADMIN_USER=${SQL_ADMIN_USER:-sa}
      - SQL_ADMIN_PASSWORD=${SQL_ADMIN_PASSWORD}
      - SQL_AUTH=${SQL_AUTH}
      - DB_USER_NAME=${DB_USER_NAME:-opconsam}
      - DB_PASSWORD=${DB_PASSWORD:?DB_PASSWORD}
      - DB_SERVER_NAME=${CONTAINER_PREFIX:-opcon}-mssql
      - DATABASE_NAME=${DATABASE_NAME:-OpConxps}
      - DB_CONFIGURATION=${DB_CONFIGURATION}
      - DB_SETUP=${DB_SETUP:-true}
      - DB_LOGICAL_DATA_FILENAME=${DB_LOGICAL_DATA_FILENAME}
      - PATH_TO_DATABASE_DATA_FILE=/var/opt/mssql/data/${DATABASE_NAME:-OpConxps}_Data.MDF
      - DB_LOGICAL_LOG_FILENAME=${DB_LOGICAL_LOG_FILENAME}
      - PATH_TO_DATABASE_LOG_FILE=/var/opt/mssql/data/${DATABASE_NAME:-OpConxps}_Log.LDF
      - SMTP_SERVER_NAME=${SMTP_SERVER_NAME}
      - NOTIFY_EMAIL_ADDRESS=${NOTIFY_EMAIL_ADDRESS}
      - NOTIFY_DOMAIN_NAME=${NOTIFY_DOMAIN_NAME}
      - CREATE_API_CERTIFICATE=${CREATE_API_CERTIFICATE:-true}
      - API_USES_TLS=${API_USES_TLS}
      - API_CERTIFICATE_PATH=${API_CERTIFICATE_PATH}
      - API_CERTIFICATE_PASSWORD=${API_CERTIFICATE_PASSWORD}
      - TZ=${TZ:-UTC}
      - LICENSE=${LICENSE}
      - ENABLE_LDAPMON=${ENABLE_LDAPMON}
      - NO_RUN=${NO_RUN}
    volumes:
      - $VOLUME_PATH/core/config:/app/config
      - $VOLUME_PATH/core/log:/app/log
    ports:
      - "${WEB_PORT:-443}:9010"
    restart: always
volumes:
  opcon-mssql:
    name: ${CONTAINER_PREFIX:-opcon}-mssql
