version: '3.7'
networks:
  default:
    name: ${ContainerPrefix:-opcon}-network
services:
  opcon-mssql:
    image: mcr.microsoft.com/mssql/server:${MssqlVersion:-2017-latest}
    container_name: ${ContainerPrefix:-opcon}-mssql
    hostname: ${MssqlHostname:-opcon-mssql}
    volumes:
      - type: volume
        source: opcon-mssql
        target: /var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DatabasePassword:?DatabasePassword}
    ports:
      - "${MssqlPort:-1433}:1433"
    restart: always
  opcon-core:
    image: smaengineering.azurecr.io/opcon:${OpconVersion:-19.1.1-latest}
    container_name: ${ContainerPrefix:-opcon}-core
    hostname: ${OpconHostname:-opcon-core}
    depends_on:
      - opcon-mssql
    environment:
      - DatabaseName=${DatabaseName:-OpConxps}
      - OpConxpsDBServerName=${ContainerPrefix:-opcon}-mssql
      - OpConxpsSQLInstance=${ContainerPrefix:-opcon}-mssql
      - DBLogicalDataFilename=${DatabaseName:-OpConxps}_Data
      - DBLogicalLogFilename=${DatabaseName:-OpConxps}_Log
      - PathToDatabaseDataFile=/var/opt/mssql/data/${DatabaseName:-OpConxps}_Data.MDF
      - PathToDatabaseLogFile=/var/opt/mssql/data/${DatabaseName:-OpConxps}_Log.LDF
      - SmWebSsl=${SmWebSsl}
      - SmWebPort=${SmWebPort}
    volumes:
      - $VolumePath/core/config:/app/config
      - $VolumePath/core/log:/app/log
    command: [ "-t", "${Timezone:-UTC}", "-c", "-d", "-u", "${DatabaseUser:-sa}", "-p", "${DatabasePassword}", "-P", "${DatabasePasswordEncrypted}", "-l", "${LicenseKey}", "-L", "${LicenseName:-0}" ]
    ports:
      - "${ApiPort:-9010}:9010"
      - "${SmWebPort:-8181}:${SmWebPort:-8181}"
    restart: always
volumes:
  opcon-mssql:
    name: ${ContainerPrefix:-opcon}-mssql
