version: '3.7'
networks:
  default:
    name: ${ContainerPrefix:-opcon}-network
services:
  config:
    image: debian:stable-slim
    container_name: ${ContainerPrefix:-opcon}-config
    hostname: ${ContainerPrefix:-opcon}-config
    volumes:
      - ${$VolumePath:?$VolumePath}/core/config:/mnt
    command: [ "/bin/sh", "-c", "test -f initialized || (touch initialized && echo 'Server=${ContainerPrefix:-opcon}-mssql; Database=${DatabaseName:-OpConxps}; User Id=${DatabaseUser:-sa}; Password=${DatabasePasswordEncrypted:?DatabasePasswordEncrypted};' > /mnt/SMAODBCConfiguration.DAT && apt-get update && apt-get install -y --no-install-recommends xxd && rm -rf /var/lib/apt/lists/* && echo '${LicenseKey:?LicenseKey}' | xxd -r -p > /mnt/${LicenseName:-0}.lic)" ]
  mssql:
    image: mcr.microsoft.com/mssql/server:${MssqlVersion:-2017-latest}
    container_name: ${ContainerPrefix:-opcon}-mssql
    hostname: ${ContainerPrefix:-opcon}-mssql
    volumes:
      - opcon-data: /var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DatabasePassword:?DatabasePassword}
    restart: always
  opcon:
    image: smaengineering.azurecr.io/opcon:${OpconVersion:-19.1.0.10243}
    container_name: ${ContainerPrefix:-opcon}-core
    hostname: ${ContainerPrefix:-opcon}-core
    depends_on:
      - config
      - mssql
    environment:
      - DatabaseName=${DatabaseName:-OpConxps}
      - OpConxpsDBServerName=${ContainerPrefix:-opcon}-mssql
      - OpConxpsSQLInstance=${ContainerPrefix:-opcon}-mssql
      - DBLogicalDataFilename=${DatabaseName:-OpConxps}_Data
      - DBLogicalLogFilename=${DatabaseName:-OpConxps}_Log
      - PathToDatabaseDataFile=/var/opt/mssql/data/${DatabaseName:-OpConxps}_Data.MDF
      - PathToDatabaseLogFile=/var/opt/mssql/data/${DatabaseName:-OpConxps}_Log.LDF
    volumes:
      - $VolumePath/core/config:/app/config
      - $VolumePath/core/log:/app/log
    command: [ "-c", "-d", "-u", "${DatabaseUser:-sa}", "-p", "${DatabasePassword}" ]
    ports:
      - "${ApiPort:-9010}:9010"
      - "${SmWebPort:-8181}:8181"
    restart: always
volumes:
  opcon-data:
