kubectl delete rs opcon
kubectl delete rs mssql
kubectl delete svc opcon
kubectl delete svc mssql
kubectl delete cm opcon-env
kubectl delete cm mssql-env
kubectl delete secrets db-passwords
kubectl delete pvc opconconfig
kubectl delete pvc opconlog
kubectl delete pvc opcondata
